{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-whirl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/whirl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/whirl/whirl_{{ version }}.tar.gz
  sha256: dc8f5eb8f056a3ec080a9671faa11f04a08810544d7fea048781d201214e5317

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    # The libstdc++.dll provided in libstdcxx v15.1.0 build h904f734_2
    # is missing `_ZSt21ios_base_library_initv`.
    # see: conda-forge/ctng-compilers-feedstock#174
    - libstdcxx !=14.3.0,!=15.1.0  # [win]
  host:
    - r-base
    - r-r6 >=2.4.0
    - r-callr
    - r-cli
    - r-dplyr
    - r-jsonlite
    - r-kableextra
    - r-knitr
    - r-purrr
    - r-quarto
    - r-reticulate
    - r-rlang
    - r-sessioninfo
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-unglue
    - r-withr
    - r-yaml
    - r-zephyr >=0.1.1
  run:
    - r-base
    - r-r6 >=2.4.0
    - r-callr
    - r-cli
    - r-dplyr
    - r-jsonlite
    - r-kableextra
    - r-knitr
    - r-purrr
    - r-quarto
    - r-reticulate
    - r-rlang
    - r-sessioninfo
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-unglue
    - r-withr
    - r-yaml
    - r-zephyr >=0.1.1
  run_constrained:
    - libstdcxx !=14.3.0,!=15.1.0           # [win]

test:
  commands:
    - $R -e "library('whirl')"           # [not win]
    - "\"%R%\" -e \"library('whirl')\""  # [win]

about:
  home: https://novonordisk-opensource.github.io/whirl/, https://github.com/novonordisk-opensource/whirl
  license: Apache-2.0
  summary: Logging of scripts suitable for clinical trials using 'Quarto' to create nice human readable logs. 'whirl' enables execution of scripts in batch, while simultaneously creating logs for the execution of each script, and providing an overview summary log of the entire batch execution.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
